import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Fira_Code({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script src="https://app.codly.com.br/codly.js?companyId=KjEmTBy2LA1zULXOWU1k&env=Development"></Script>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
